apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: basic-example-cluster-auto-flink
  namespace: flink-team-a-ns
spec:
  imagePullPolicy: Always
  emrReleaseLabel: "emr-7.0.0-flink-latest"
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    # Autotuning parameters
    kubernetes.operator.job.autoscaler.autotune.enable: "true"
    kubernetes.operator.job.autoscaler.autotune.metrics.history.max.count: "2"
    kubernetes.operator.job.autoscaler.autotune.metrics.restart.count: "1"
    metrics.job.status.enable: TOTAL_TIME

    # Autoscaler parameters
    kubernetes.operator.job.autoscaler.enabled: "true"
    kubernetes.operator.job.autoscaler.scaling.enabled: "true"
    kubernetes.operator.job.autoscaler.stabilization.interval: "5s"
    kubernetes.operator.job.autoscaler.metrics.window: "1m"

    jobmanager.scheduler: adaptive
    # Replace with s3 bucket in your own account
    state.checkpoints.dir: s3://emr-flink-data/checkpoints
    state.savepoints.dir: s3://emr-flink-data/savepoints


  executionRoleArn: arn:aws:iam::xxxxxxxxx:role/emr-eks-flink-flink-team-a-20240406012025932700000008
  jobManager:
    # Replace with s3 bucket in your own account
    storageDir: s3://emr-flink-data/data/basic-example-app-cluster/jobmanager
    resource:
      memory: "2048m"
      cpu: 1

  taskManager:
    replicas: 2
    resource:
      memory: "2048m"
      cpu: 1

  job:
    # if you have your job jar in S3 bucket you can use that path as well
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    parallelism: 4
    upgradeMode: savepoint
    savepointTriggerNonce: 0
  monitoringConfiguration:
    s3MonitoringConfiguration:
      logUri: emr-flink-data/logs
    cloudWatchMonitoringConfiguration:
       logGroupName: /aws/emr-flink/flink-team-a
    sideCarResources:
      limits:
        cpuLimit: 500m
        memoryLimit: 250Mi
    containerLogRotationConfiguration:
        rotationSize: 2GB
        maxFilesToKeep: "10"
