apiVersion: v1
kind: Pod
metadata:
  name: <job_name>-executor
  namespace: emr-ml-team-a

spec:
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local1
        type: Directory

  nodeSelector:
    NodeGroupType: "spark-ubuntu-gpu-ca"
    topology.kubernetes.io/zone: "us-west-2a"

  containers:
    - name: spark-kubernetes-executor # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-1
          mountPath: /data1
          readOnly: false

  tolerations:
    - key: "spark-ubuntu-gpu-ca"
      operator: "Exists"
      effect: "NoSchedule"
