{{- if .Values.nodePool.enabled }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.name }}
spec:
  template:
    metadata:
      labels:
        NodePool: {{ .Values.name }}
        NodeGroupType: {{ .Values.name }}
        {{- with .Values.nodePool.labels }}
        {{- range . }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      nodeClassRef:
        name: {{ .Values.name }}
      {{- with .Values.nodePool.taints }}
      taints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: {{ toYaml .Values.nodePool.instanceFamilies | nindent 12 }}
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: {{ toYaml .Values.nodePool.instanceSizes | nindent 12 }}
        - key: "kubernetes.io/arch"
          operator: In
          values: {{ toYaml .Values.nodePool.architecture | nindent 12 }}
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: {{ toYaml .Values.nodePool.azs | nindent 12 }}
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: {{ toYaml .Values.nodePool.capacityTypes | nindent 12 }}
  disruption:
    consolidationPolicy: {{ .Values.nodePool.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.nodePool.disruption.consolidateAfter }}
    expireAfter: {{ .Values.nodePool.disruption.expireAfter }}
  limits:
    cpu: {{ .Values.nodePool.limits.cpu }}
    memory: {{ .Values.nodePool.limits.memory }}
  weight: {{ .Values.nodePool.weight }}
{{- end }}
