---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.name }}
spec:
  template:
    metadata:
      labels:
        NodePool: {{ .Values.name }}
        NodeGroupType: {{ .Values.name }}
        {{- with .Values.labels }}
        {{- range . }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      nodeClassRef:
        name: {{ .Values.name }}
      {{- with .Values.taints }}
      taints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          {{- with .Values.instanceFamilies }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          {{- with .Values.instanceSizes }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - key: "kubernetes.io/arch"
          operator: In
          values: {{ toYaml .Values.architecture | nindent 12 }}
        - key: "topology.kubernetes.io/zone"
          operator: In
          {{- with .Values.azs }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: {{ toYaml .Values.capacityTypes | nindent 12 }}
  disruption:
    consolidationPolicy: {{ .Values.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.disruption.consolidateAfter }}
    expireAfter: {{ .Values.disruption.expireAfter }}
  limits:
    cpu: {{ .Values.limits.cpu }}
    memory: {{ .Values.limits.memory }}
  weight: {{ .Values.weight }}

