apiVersion: v1 
kind: PersistentVolume
metadata:
  name: efs-persist
  namespace: ${namespace}
spec:
  capacity:
    storage: 123Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${efs_id}.efs.${region}.amazonaws.com
    path: "/"