apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persist-shared
  namespace: ${namespace}
spec:
  capacity:
    storage: 123Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${efs_shared_id}.efs.${region}.amazonaws.com
    path: "/"