apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-persist
  namespace: k8-jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
