apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: efs-persist
  namespace: ${namespace}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
