---
apiVersion: v1
kind: Namespace
metadata:
  name: restore
  labels:
      name: restore
---
apiVersion: v1
kind: Secret
metadata:
  name: app-auth
  namespace: restore
type: kubernetes.io/basic-auth
stringData:
  username: app      # required field for kubernetes.io/basic-auth
  password: testing # required field for kubernetes.io/basic-auth
