apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-pod
  template:
    metadata:
      labels:
        app: ssh-pod
    spec:
      containers:
      - name: ssh-server
        image: linuxserver/openssh-server
        ports:
        - containerPort: 22 # SSH server runs on port 22
        # Add additional configurations as needed, such as volume mounts, environment variables, etc.
