run:
  name: download_gpt3_pile
  results_dir: /home/ec2-user/environment/nemo-megatron-launcher/launcher_scripts/results/download_gpt3_pile
  time_limit: '4:00:00'
  dependency: singleton
  node_array_size: 2
  array: 0-29
  bcp_preproc_npernode: 2
dataset: pile
download_the_pile: true
the_pile_url: https://huggingface.co/datasets/monology/pile-uncopyrighted/resolve/main/train/
file_numbers: 0-29
preprocess_data: true
download_vocab_url: https://huggingface.co/gpt2/resolve/main/vocab.json
download_merges_url: https://huggingface.co/gpt2/resolve/main/merges.txt
vocab_save_dir: /home/ec2-user/environment/nemo-megatron-launcher/launcher_scripts/data/bpe
merges_save_dir: /home/ec2-user/environment/nemo-megatron-launcher/launcher_scripts/data/bpe
tokenizer_type: GPT2BPETokenizer
rm_downloaded: true
rm_extracted: true
data_dir: /home/ec2-user/environment/nemo-megatron-launcher/launcher_scripts/data
cluster_type: k8s
launcher_scripts_path: /home/ec2-user/environment/nemo-megatron-launcher/launcher_scripts
data_config: download_gpt3_pile
