apiVersion: v1
kind: PersistentVolume
metadata: 
  name: gp2-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:  
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: gp2
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: auto
