# Shared values
name: default
clusterName:

# EC2NodeClass specific values
ec2NodeClass:
  enabled: true
  amiFamily: AL2
  amiSelectorTerms:
  subnetSelectorTags:
    kubernetes.io/role/internal-elb: "1"  # Added here to make sure that will be scheduled in private subnets
  karpenterRole:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDevice:
    deviceName: /dev/xvda
    volumeSize: 100Gi
    volumeType: gp3
    encrypted: true
    deleteOnTermination: true
  detailedMonitoring: true
  userData:

# NodePool specific values
nodePool:
  enabled: true
  labels:
  taints:
  - key: aws.amazon.com/neuroncore
    value: "true"
    effect: "NoSchedule"
  - key: aws.amazon.com/neuron
    value: "true"
    effect: "NoSchedule"
  - key: hub.jupyter.org/dedicated # According to optimization docs https://z2jh.jupyter.org/en/latest/administrator/optimization.html
    operator: "Equal"
    value: "user"
    effect: "NoSchedule"
  instanceFamilies: ["c5", "m5", "r5"]
  instanceSizes: ["xlarge", "2xlarge", "4xlarge", "8xlarge", "16xlarge", "24xlarge"]
  architecture: ["amd64"]
  azs: [""]
  capacityTypes: ["spot", "on-demand"]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 720h
  limits:
    cpu: "1000"
    memory: 1000Gi
  weight: 10
