apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "neuron-device-plugin.fullname" . }}
  labels:
{{ include "neuron-device-plugin.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "neuron-device-plugin.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "neuron-device-plugin.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
