{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "neuron-device-plugin.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "neuron-device-plugin.labels" . | indent 4 }}
{{- end -}}
