prometheus:
  prometheusSpec:
    retention: 5h
    scrapeInterval: 30s
    evaluationInterval: 30s
    scrapeTimeout: 10s
    additionalScrapeConfigs:
      - job_name: kubecost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
          - names:
              - kubecost-cost-analyzer.kubecost.svc
            type: 'A'
            port: 9003
alertmanager:
 enabled: false
grafana:
  enabled: true
  defaultDashboardsEnabled: false
