prometheus:
  prometheusSpec:
    retention: 5h
    scrapeInterval: 30s
    evaluationInterval: 30s
    scrapeTimeout: 10s
    additionalScrapeConfigs:
      - job_name: 'nifi'
        scrape_interval: 15s
        metrics_path: '/metrics'
        static_configs:
          - targets:
              - nifi-metrics.nifi.svc.cluster.local:9092
alertmanager:
 enabled: false
grafana:
  enabled: true
  defaultDashboardsEnabled: false
