proxy:
  https:
    enabled: true
    type: offload
  service:
    annotations:
      # Certificate ARN
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${ssl_cert_arn}
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      # Which ports should use SSL
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
singleuser:
  image:
    name: jupyter/base-notebook
    tag: latest
  storage:
    type: "static"
    static:
      pvcName: "efs-persist"
      subPath: "home/{username}"
    extraVolumes:
    - name: jupyterhub-shared
      persistentVolumeClaim:
        claimName: efs-persist-shared
    extraVolumeMounts:
    - name: jupyterhub-shared
      mountPath: /etc/shared
      readOnly: false
  extraEnv:
    CHOWN_HOME: "yes"
    CHOWN_EXTRA: "/etc/shared"
  uid: 0
  fsGid: 0
  cmd: "start-singleuser.sh" 
hub:
  config:
    GenericOAuthenticator:
      oauth_callback_url: ${jupyterdomain}
      client_id: ${client_id}
      client_secret: ${client_secret}
      authorize_url: ${authorize_url}
      token_url: ${token_url}
      userdata_url: ${userdata_url}
      scope:
        - openid
        - email
      username_key: "username"
      login_service : "AWS Cognito"
      userdata_method: "POST"
    JupyterHub:
      authenticator_class: generic-oauth
