apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-kubernetes-operator-monitor
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - flink-kubernetes-operator
  selector:
    matchLabels:
      app.kubernetes.io/name: flink-kubernetes-operator
  podMetricsEndpoints:
    - port: metrics
